### ISSUE TITLE
Rust 分支无法导入 jieba_navi_rs 模块

### ISSUE THREAD

**Issue by bigshans** [kkew3/jieba.vim#1]
![图片](https://github.com/user-attachments/assets/66a58a21-9c6e-4112-93b5-9a427d3b9279)

**Comment by kkew3** [comment]
我刚刚做了一次 `:PlugUpdate jieba.vim`，在我本地没有复现出你截图的问题。从你的截图上看你很可能用的是 caf44f8 之前的某次提交。请充分阅读 README 的[安装](https://github.com/kkew3/jieba.vim/blob/rust/README.md#%E5%AE%89%E8%A3%85)章节，以及 `git pull` 代码到最新的 `rust` 分支，例如通过 `:PlugUpdate jieba.vim`。

如果你是打开 `vim` 即报错，那么应该是没有 `PlugUpdate jieba.vim`（假定你用的是 `vim-plug`）。请确保 `~/.vimrc` 中是这么写的：`Plug 'kkew3/jieba.vim', { 'branch': 'rust', 'do': './build.sh' }`

**Comment by bigshans** [comment]
你是在哪个平台编译的？我是在 Linux 上编译的。

```rust
        let dylib_src = "../target/release/libjieba_navi_rs.dylib";
```

我的 release 中没有 dylib 文件，只有 so 文件和 .d 文件。

![图片](https://github.com/user-attachments/assets/6cf5d096-8d0a-4c7c-a9b7-a3b7433fa293)

**Comment by kkew3** [comment]
明白了，刚开始做，确实没考虑跨平台问题。我是在 macOS 上。你可以暂时参考 [pyo3 文档](https://pyo3.rs/v0.22.2/building-and-distribution.html#manual-builds) 把

https://github.com/kkew3/jieba.vim/blob/6a719a9fe6f0526760f1b1ae3653bec34d771eab/pythonx/build.rs#L48

改为

```rust
let dylib_src = "../target/release/libjieba_navi_rs.so";
```

其它应该不用变。然后尝试重新编译。这两天我改一下 `build.rs`。

**Comment by kkew3** [comment]
我在 ubuntu 上现在编译是可以的，打开 vim 也没有报错。如果没问题了的话把这个 issue 关掉即可。
